### ISSUE TITLE
Add Citadel.one

### ISSUE THREAD

**Issue by Krewedk0** [berachain/default-lists#119]
- [x] I understand that filing an issue does not guarantee addition to the Berachain default validator list.
- [x] I will not ping the Discord about this listing request.

**Please follow the format for your validator.**

```json
{
    "id": "0x2c11C4C97ca866d64CC09Ea2dcD76f2D2EC6Ae55",
    "logoURI": "https://raw.githubusercontent.com/cosmostation/chainlist/master/chain/cosmos/moniker/cosmosvaloper1lzhlnpahvznwfv4jmay2tgaha5kmz5qxerarrl.png",
    "name": "Citadel.one",
    "description": "Citadel.one is a multi-asset non-custodial staking platform that lets anyone become a part of decentralized infrastructure and earn passive income. Stake with our nodes or any other validator across multiple networks in a few clicks.",
    "website": "https://citadel.one",
    "twitter": "https://twitter.com/CitadelDAO"
},
```

- id: validator fee recipient
- logoURI: path to validator icon in default-list repo
- name: validator name
- description (optional): a short description for the validator
- website (optional): a validator's website
- twitter (optiona): a validator's twitter account url

this repository is uploaded to cloudinary for improved availability. Please upload your relevant assets under the `assets/` folder and prefix the path in this json file with `https://res.cloudinary.com/duv0g402y/raw/upload/`.

an example :
`https://res.cloudinary.com/duv0g402y/raw/upload/src/assets/${asset_file_name}`
ℹ️ AFTER OPENING AN ISSUE, CREATE A BRANCH AND ADD YOUR CHANGES. WHEN READY, CREATE A PR AND LINK YOUR ISSUE IN THE PR 🚀

**Comment by corduroybera** [comment]
@Krewedk0 please fork the repo and create a pr for a branch with your changes
