### ISSUE TITLE
Add BlockPI Network

### ISSUE THREAD

**Issue by blockPI-rayn** [berachain/default-lists#133]
- [x] I understand that filing an issue does not guarantee addition to the Berachain default validator list.
- [x] I will not ping the Discord about this listing request.

**Please follow the format for your validator.**

```json
{
    "id": "0x364020282B9A82f6Be32fd20Ff829b7F0AacD118",
    "logoURI": "https://raw.githubusercontent.com/blockPI-rayn/blockPI-rayn/main/BlockPI%20Network.jpg",
    "name": "BlockPI Network",
    "description": "Distributed multi-chain acceleration layer. Solving the RPC requests congestion problem with infinite scalability.",
    "website": "https://blockpi.io/",
    "twitter": "https://twitter.com/RealBlockPI"
},
```

- id: validator fee recipient
- logoURI: path to validator icon in default-list repo
- name: validator name
- description (optional): a short description for the validator
- website (optional): a validator's website
- twitter (optiona): a validator's twitter account url

this repository is uploaded to cloudinary for improved availability. Please upload your relevant assets under the `assets/` folder and prefix the path in this json file with `https://res.cloudinary.com/duv0g402y/raw/upload/`.

an example :
`https://res.cloudinary.com/duv0g402y/raw/upload/src/assets/${asset_file_name}`
ℹ️ AFTER OPENING AN ISSUE, CREATE A BRANCH AND ADD YOUR CHANGES. WHEN READY, CREATE A PR AND LINK YOUR ISSUE IN THE PR 🚀

**Comment by corduroybera** [comment]
@blockPI-rayn please fork the repo and create a PR with your changes

**Comment by blockPI-rayn** [comment]
> @blockPI-rayn please fork the repo and create a PR with your changes

ok

**Comment by blockPI-rayn** [comment]
https://github.com/berachain/default-lists/pull/249
