### ISSUE TITLE
Add DOUBLETOP

### ISSUE THREAD

**Issue by razumv** [berachain/default-lists#138]
- [x] I understand that filing an issue does not guarantee addition to the Berachain default validator list.
- [x] I will not ping the Discord about this listing request.

**Please follow the format for your validator.**

```json
{
    "id": "0xe868bE65C50b61E81A3fC5cB5A7916090B05eb2A",
    "logoURI": "https://doubletop-bin.ams3.digitaloceanspaces.com/2top.png",
    "name": "DOUBLETOP",
    "description": "Your trusted security non-custodial validator. DOUBLETOP is Ukrainian crypto-oriented holding.",
    "website": "https://doubletop.io/",
    "twitter": "https://x.com/doubletop_io"
},
```

- id: validator fee recipient
- logoURI: path to validator icon in default-list repo
- name: validator name
- description (optional): a short description for the validator
- website (optional): a validator's website
- twitter (optiona): a validator's twitter account url

this repository is uploaded to cloudinary for improved availability. Please upload your relevant assets under the `assets/` folder and prefix the path in this json file with `https://res.cloudinary.com/duv0g402y/raw/upload/`.

an example :
`https://res.cloudinary.com/duv0g402y/raw/upload/src/assets/${asset_file_name}`
ℹ️ AFTER OPENING AN ISSUE, CREATE A BRANCH AND ADD YOUR CHANGES. WHEN READY, CREATE A PR AND LINK YOUR ISSUE IN THE PR 🚀

**Comment by corduroybera** [comment]
@razumv please fork the repo and create a branch with your changes

**Comment by razumv** [comment]
@corduroybera forked and added. https://github.com/berachain/default-lists/pull/269 please review
