### ISSUE TITLE
Add stakefish

### ISSUE THREAD

**Issue by wilsonf2pool** [berachain/default-lists#139]
- [x] I understand that filing an issue does not guarantee addition to the Berachain default validator list.
- [x] I will not ping the Discord about this listing request.

**Please follow the format for your validator.**

```json
{
    "id": "0x93174B2DaD595F35582cC62FCBf96b86709863D5",
    "logoURI": "https://raw.githubusercontent.com/stakefish/eigenlayer-metadata/main/stakefish.png",
    "name": "stakefish",
    "description": "We are the leading staking service provider for blockchain projects. Join our community to help secure networks and earn rewards. Stake. Earn. Relax.",
    "website": "https://stake.fish/",
    "twitter": "https://twitter.com/stakefish"
},
```

- id: validator fee recipient
- logoURI: path to validator icon in default-list repo
- name: validator name
- description (optional): a short description for the validator
- website (optional): a validator's website
- twitter (optiona): a validator's twitter account url

this repository is uploaded to cloudinary for improved availability. Please upload your relevant assets under the `assets/` folder and prefix the path in this json file with `https://res.cloudinary.com/duv0g402y/raw/upload/`.

an example :
`https://res.cloudinary.com/duv0g402y/raw/upload/src/assets/${asset_file_name}`
ℹ️ AFTER OPENING AN ISSUE, CREATE A BRANCH AND ADD YOUR CHANGES. WHEN READY, CREATE A PR AND LINK YOUR ISSUE IN THE PR 🚀

**Comment by corduroybera** [comment]
@wilsonf2pool please fork the repo and create a pr with your changes
