### ISSUE TITLE
Add {Ebunker}

### ISSUE THREAD

**Issue by nas-work** [berachain/default-lists#82]
- [x] I understand that filing an issue does not guarantee addition to the Berachain default validator list.
- [x] I will not ping the Discord about this listing request.

**Please follow the format for your validator.**

```json
{
    "id": "0x7e8d2356240A1F0e249e628b6964C6227a11d945",
    "logoURI": "https://raw.githubusercontent.com/winniewdd/winniewdd/main/Ebunker-logo/ebunker-logo.png",
    "name": "Ebunker",
    "description": "Ebunker is a leading node operator and blockchain infrastructure company.",
    "website": "https://www.ebunker.io/",
    "twitter": "https://twitter.com/ebunker_eth"
},
```

- id: validator fee recipient
- logoURI: path to validator icon in default-list repo
- name: validator name
- description (optional): a short description for the validator
- website (optional): a validator's website
- twitter (optiona): a validator's twitter account url

this repository is uploaded to cloudinary for improved availability. Please upload your relevant assets under the `assets/` folder and prefix the path in this json file with `https://res.cloudinary.com/duv0g402y/raw/upload/`.

an example :
`https://res.cloudinary.com/duv0g402y/raw/upload/src/assets/${asset_file_name}`
ℹ️ AFTER OPENING AN ISSUE, CREATE A BRANCH AND ADD YOUR CHANGES. WHEN READY, CREATE A PR AND LINK YOUR ISSUE IN THE PR 🚀

**Comment by nas-work** [comment]
Add staked

**Comment by corduroybera** [comment]
@nas-work please fork the repo and add a branch with your changes
